#!/usr/bin/env node
import program from "commander";
import { create } from "./create";
import { update } from "./update";
import { cron } from "./cron";

program.version(require("../package.json").version);

program.
    command("create <functionName>").
    description("Create a project `here` for a new AWS Lambda").
    action(function (functionName, opts) {
        create(functionName, opts);
    });

program.
    command("update").
    description("Update configuration for AWS Lambda").
    action(function (opts) {
        update(opts);
    });

program.
    command("cron <ruleName>").
    description("Setup cron scheduled job via AWS CloudWatch Event").
    action(function (ruleName, opts) {
        cron(ruleName, opts);
    });

program.
    command("info").
    description("Show information about configuration").
    action(function (opts) {
        const meta = require(`${process.cwd()}/.lambdarc.json`);
        console.log(JSON.stringify(meta.config, null, "  "));
        console.log(JSON.stringify(meta.trigger, null, "  "));
    });

program.parse(process.argv);
